Add functions for html conversion and notebook stripping
crim-ca/notebook-utils pull request #2
Opened 2022-04-29 20:39 UTC by antoine-daigneault-demers

2022-04-29 21:04 UTC, fmigneault requested changes
Any failing execution returns `exit 0` leaving the false impression it succeeded. 
This is even more a problem with loops since operation can be only partially done.

Consider replacing arguments like `-file` to `-f`/`--file` (same for other arguments).
The single `-` is usually employed as shortcut for `--` long names.

2022-04-29 21:04 UTC, fmigneault commented on src/notebook_utils/automation.py
> +        "-doc",
`-d,--directory` or `-o,--output` would be more appropriate.
This output does not seem related to documentation.

2022-04-29 21:04 UTC, fmigneault commented on src/notebook_utils/automation.py
> +            strip_notebook(notebook_file)
If any notebook fails, it returns with no error status. Process is incomplete and reported as all success.

2022-04-29 21:04 UTC, fmigneault commented on src/notebook_utils/automation.py
> +    strip_notebook(args.file)
Failure returns status without error.

2022-04-29 21:04 UTC, fmigneault commented on src/notebook_utils/automation.py
> +    notebook_to_html(args.file, args.doc)
No error

2022-04-29 21:04 UTC, fmigneault commented on src/notebook_utils/automation.py
> +            notebook_to_html(notebook_file, args.doc)
No error

2022-04-29 21:06 UTC, fmigneault requested changes
Failing operations do not return the non zero error code.
When looping files, process could look like it succeeded although it worked only for part of the files.

The arguments with single `-` should be replaced by `--` long notation. 
The short notation (e.g.: `-f` for `--file`) can also be added.

2022-05-02 20:17 UTC, antoine-daigneault-demers commented
Should I return an error message in addition to an exit code 1 on errors?

RIght now the errors from the commands themselves show up in the console, is it enough?

2022-05-03 19:48 UTC, fmigneault commented
> Should I return an error message in addition to an exit code 1 on errors?
> 
> RIght now the errors from the commands themselves show up in the console, is it enough?

A simple message could be printed to help indicate what went wrong, but not the full exception traceback to make CLI "cleaner". 
The return value should be only the error code. There could be some verbosity flags to print more or less information using for example logger levels (example: https://github.com/crim-ca/weaver/blob/master/weaver/cli.py#L989-L1030).

2022-05-03 21:15 UTC, fmigneault reviewed
Only check to add some logging details. The rest is fine.

2022-05-03 21:15 UTC, fmigneault commented on src/notebook_utils/automation.py
> +            exit_status.append(strip_notebook(notebook_file))
To help the user, you should add an error log of which notebook file had a problem.
Same thing for the other CLI loop.

2022-05-06 20:25 UTC, antoine-daigneault-demers commented
Thanks for the feedback!

2022-05-10 21:21 UTC, fmigneault reviewed
Looks fine. Just need to patch the logger calls and good to merge.

2022-05-10 21:21 UTC, fmigneault commented on src/notebook_utils/automation.py
> +    _logger.info(f"Converting {args.file}.")
Logger parameters should use this format to take advantage of skipping string formatting if level is disabled:
```python
_logger.info("Converting %s.", args.file)
```

(other places to edit as well)

2022-05-11 18:42 UTC, fmigneault approved these changes

2022-05-11 18:43 UTC, fmigneault commented
Make sure to apply the version tag after merge.

2022-05-11 19:02 UTC, merged